name: Build

permissions:
  contents: write

on:
  push:
    branches: [ "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Push dev to main
        run: |
          set -xe
          git fetch origin main
          git checkout main
          git pull origin main
          git merge --ff-only dev
          git push origin main