name: Build on main

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test of chained CI actions
        run: |
          echo "Hello world!"